// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication1.shared.infrastructure;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241119230949_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.group.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("92769f04-1066-473d-9417-7174c7a10665"),
                            Description = "aespa is a 4-member girl group (Karina, Giselle, Winter, Ningning) from SM Entertainment that debuted on Nov 17th, 2020 with \"Black Mamba.\"\n\nLargely thought to be one of the groups that “started the 4th gen of K-Pop,” aespa is recognized for their theme of AIs and virtual reality. Throughout their album art, lyrics, music videos, and concept films, aespa has established unique lore of their own, drawing inspiration from sub-culture genres such as cyberpunk and frutiger aero, reminiscent of the Y2K trend.\n\naespa’s discography spans a variety of genres - including electronica, synthpop, hyperpop, trap, hiphop, R&B, and more.",
                            Name = "aespa",
                            Photo = "https://www.ipduck-kpop.wiki/content/images/size/w1600/2024/05/GNEEkD4bgAASBoV.jpg"
                        });
                });

            modelBuilder.Entity("WebApplication1.idol.Idol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Idols");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a13b391a-d730-46c4-ad89-2b4901f4e0f8"),
                            GroupId = new Guid("92769f04-1066-473d-9417-7174c7a10665"),
                            Name = "Karina",
                            Photo = "https://www.ipduck-kpop.wiki/content/images/size/w1600/2024/05/krn.jpeg",
                            RealName = "Yoo Ji-min"
                        },
                        new
                        {
                            Id = new Guid("3f05982f-7bf5-4af1-bd2a-75eb1eaecb52"),
                            GroupId = new Guid("92769f04-1066-473d-9417-7174c7a10665"),
                            Name = "Giselle",
                            Photo = "https://www.ipduck-kpop.wiki/content/images/size/w1600/2024/05/gs.jpeg",
                            RealName = "Aeri Uchinaga"
                        },
                        new
                        {
                            Id = new Guid("68040591-2641-4642-9c84-527f32ee06d1"),
                            GroupId = new Guid("92769f04-1066-473d-9417-7174c7a10665"),
                            Name = "Winter",
                            Photo = "https://www.ipduck-kpop.wiki/content/images/size/w1600/2024/05/wt.jpeg",
                            RealName = "Kim Min-jeong"
                        },
                        new
                        {
                            Id = new Guid("2e353720-1967-4597-a945-9946f685ff8a"),
                            GroupId = new Guid("92769f04-1066-473d-9417-7174c7a10665"),
                            Name = "Ningning",
                            Photo = "https://www.ipduck-kpop.wiki/content/images/size/w1600/2024/05/nn.jpeg",
                            RealName = "Níng Yìzhuó"
                        });
                });

            modelBuilder.Entity("WebApplication1.idol.Idol", b =>
                {
                    b.HasOne("WebApplication1.group.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
